# Changes here will be overwritten by Copier
_commit: 1be0baf
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: '2023'
documentation: true
email: nick@koston.org
full_name: J. Nick Koston
github_username: bdraco
has_cli: false
initial_commit: true
open_source_license: Apache Software License 2.0
package_name: aiohttp_fast_url_dispatcher
project_name: aiohttp-fast-url-dispatcher
project_short_description: A faster URL dispatcher for aiohttp
project_slug: aiohttp-fast-url-dispatcher
run_poetry_install: true
setup_github: true
setup_pre_commit: true

